_target_: src.models.xresunet_module.XResUNetLitModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.xresnet_unet.XResUNet
  input_size: [64,64]
  forecast_steps: 24
  history_steps: 9
  pretrained: False
