_target_: src.datamodules.xresunet_datamodule.SatDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 32
num_workers: 8
channels: ["IR_016", "IR_039", "IR_087", "IR_097", "IR_108", "IR_120", "IR_134", "VIS006", "VIS008", "WV_062", "WV_073"]
pin_memory: True
